name: word_search
version: 0.1.0
description: >-
    A word search puzzle generator built with dart.
    This library allows you to create a puzzle from a list of
    input words that can be arranged in many orientations.
    This library also provides a way to view and solve the puzzle.

repository: https://github.com/nisheed2440/word_search.dart
homepage: https://github.com/nisheed2440/word_search.dart
issue_tracker: https://github.com/nisheed2440/word_search.dart/issues

environment:
    sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
    test: ^1.14.5
    test_coverage: ^0.4.1